{{- if .Values.frontend.configMap.enabled -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "nginx-arbitrary-deployment.fullname" . }}
  labels:
  {{- include "nginx-arbitrary-deployment.labels" . | nindent 4 }}
data:
  nginx.conf: |
{{ .Values.frontend.configMap.nginxConf | indent 4 }}

  default.conf: |
{{ .Values.frontend.configMap.defaultConf | indent 4 }}

  .htpasswd: |
{{ .Values.frontend.configMap.htpasswd | indent 4 }}

  {{- end }}