apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-arbitrary-deployment.fullname" . }}
  labels:
    {{- include "nginx-arbitrary-deployment.labels" . | nindent 4 }}
spec:
  {{- if not .Values.frontend.autoscaling.enabled }}
  replicas: {{ .Values.frontend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nginx-arbitrary-deployment.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.frontend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nginx-arbitrary-deployment.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.frontend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nginx-arbitrary-deployment.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.frontend.podSecurityContext | nindent 8 }}
      containers:
        -                                                                                                               #HINT: closure
          name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.frontend.securityContext | nindent 12 }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /cache
              name: cache-volume
            - mountPath: /mnt
              name: pvol-volume
            - mountPath: /default.conf
              name: config-volume
              subPath: default.conf
            - mountPath: /etc/nginx/nginx.conf
              name: config-volume
              subPath: nginx.conf
            - mountPath: /.htpasswd
              name: config-volume
              subPath: .htpasswd
      volumes:
        - name: pvol-volume
          persistentVolumeClaim:
            claimName: test-pvc
        - name: cache-volume
          emptyDir: { }
        - name: config-volume
          configMap:
            name: {{ include "nginx-arbitrary-deployment.fullname" . }}
            items:
              - key: nginx.conf
                path: nginx.conf
              - key: default.conf
                path: default.conf
              - key: .htpasswd
                path: .htpasswd
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}